package uit.tkorg.crs.main;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import uit.tkorg.crs.bo.AuthorPaperBO;
import uit.tkorg.crs.dbconnection.ConnectionService;
import uit.tkorg.crs.experiment.Experiment;
import uit.tkorg.utility.TextParallelProcessor;

/**
 *
 * @author daolv
 */
public class CRSMainFrame extends javax.swing.JFrame {

    public CRSMainFrame() {
        initComponents();
        jTextFieldPathDataExtraction.setText("C:\\CRS-Experiment\\CRS-Output");
        jTextFieldStemmingSourcePath.setText("C:\\CRS-Experiment\\OutStem");
        jTextFieldStemOutPath.setText("C:\\CRS-Experiment\\OutStem");

        jCheckBoxStopword.setSelected(true);
        jCheckBoxStopword.setEnabled(false);

        jTextFieldFormatLDAPath.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneCRS = new javax.swing.JTabbedPane();
        jPanelSetting = new javax.swing.JPanel();
        jLabelDBSetting = new javax.swing.JLabel();
        jLabelHostName = new javax.swing.JLabel();
        jLabelDBMSPort = new javax.swing.JLabel();
        jLabelDBName = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldHostName = new javax.swing.JTextField();
        jTextFieldDBMSPort = new javax.swing.JTextField();
        jTextFieldDBName = new javax.swing.JTextField();
        jTextFieldDBUserName = new javax.swing.JTextField();
        jTextFieldDBPassword = new javax.swing.JTextField();
        jButtonApplyDBSetting = new javax.swing.JButton();
        jButtonChangeDBSetting = new javax.swing.JButton();
        jPanelPreProcessing = new javax.swing.JPanel();
        jLabelPreProcessing = new javax.swing.JLabel();
        jPanelDBExtraction = new javax.swing.JPanel();
        jLabelFrom = new javax.swing.JLabel();
        jLabelTo = new javax.swing.JLabel();
        jFormattedTextFieldYearFrom = new javax.swing.JFormattedTextField();
        jFormattedTextFieldYearTo = new javax.swing.JFormattedTextField();
        jButtonDBExtract = new javax.swing.JButton();
        jLabelDirPath = new javax.swing.JLabel();
        jTextFieldPathDataExtraction = new javax.swing.JTextField();
        jButtonBrowse1 = new javax.swing.JButton();
        jPanelRemoveStopwordStemming = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldStemmingSourcePath = new javax.swing.JTextField();
        jButtonBrowse2 = new javax.swing.JButton();
        jTextFieldStemOutPath = new javax.swing.JTextField();
        jCheckBoxStopword = new javax.swing.JCheckBox();
        jCheckBoxStemming = new javax.swing.JCheckBox();
        jButtonStemming = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFormatLDAPath = new javax.swing.JTextField();
        jButtonBrowse4 = new javax.swing.JButton();
        jTextFieldFormatLDAOutFile = new javax.swing.JTextField();
        jLabel_LDALib = new javax.swing.JLabel();
        jComboBoxLDALib = new javax.swing.JComboBox();
        jButtonFormatInputLDA = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanelLinkPrediction = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTrainingAuthorPaperPath = new javax.swing.JTextField();
        txtTrainingPaperYearPath = new javax.swing.JTextField();
        jButtonBrowse6 = new javax.swing.JButton();
        jButtonBrowse7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNFAuthorPaperPath = new javax.swing.JTextField();
        txtFFAuthorPaperPath = new javax.swing.JTextField();
        jButtonBrowse8 = new javax.swing.JButton();
        jButtonBrowse9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtListAuthorPath = new javax.swing.JTextField();
        jButtonBrowse10 = new javax.swing.JButton();
        radbtnUseListAuthor = new javax.swing.JRadioButton();
        radbtnRadomAuthors = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtNumberOfRandomAuthor = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jCheckBoxCosine = new javax.swing.JCheckBox();
        jCheckBoxJaccard = new javax.swing.JCheckBox();
        jCheckBoxAdamicAdar = new javax.swing.JCheckBox();
        jCheckBoxRSS = new javax.swing.JCheckBox();
        jCheckBoxMPVS = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jCheckBoxRSSPlus = new javax.swing.JCheckBox();
        jCheckBoxMPVSPlus = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        txtValueK = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtValueYear = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jCheckBoxKLDivergence = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        txtResultPath = new javax.swing.JTextField();
        jButtonBrowse11 = new javax.swing.JButton();
        jButtonRun = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        jMenuExperiment = new javax.swing.JMenu();
        jMenuItemPreProcessing = new javax.swing.JMenuItem();
        jMenuItemLinkPrediction = new javax.swing.JMenuItem();
        jMenuDBLP = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRS Framework");

        jLabelDBSetting.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDBSetting.setText("DATABASE CONNECTION SETTING");

        jLabelHostName.setText("Host name:");

        jLabelDBMSPort.setText("Port");

        jLabelDBName.setText("DB Name:");

        jLabelUserName.setText("Username:");

        jLabelPassword.setText("Password:");

        jTextFieldHostName.setText("localhost");
        jTextFieldHostName.setToolTipText("");
        jTextFieldHostName.setEnabled(false);

        jTextFieldDBMSPort.setText("3306");
        jTextFieldDBMSPort.setEnabled(false);
        jTextFieldDBMSPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDBMSPortActionPerformed(evt);
            }
        });

        jTextFieldDBName.setText("MAS");
        jTextFieldDBName.setEnabled(false);

        jTextFieldDBUserName.setText("root");
        jTextFieldDBUserName.setEnabled(false);

        jTextFieldDBPassword.setText("root");
        jTextFieldDBPassword.setEnabled(false);

        jButtonApplyDBSetting.setText("Apply");
        jButtonApplyDBSetting.setEnabled(false);
        jButtonApplyDBSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyDBSettingActionPerformed(evt);
            }
        });

        jButtonChangeDBSetting.setText("Change");
        jButtonChangeDBSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeDBSettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSettingLayout = new javax.swing.GroupLayout(jPanelSetting);
        jPanelSetting.setLayout(jPanelSettingLayout);
        jPanelSettingLayout.setHorizontalGroup(
            jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingLayout.createSequentialGroup()
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSettingLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButtonApplyDBSetting)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonChangeDBSetting))
                    .addGroup(jPanelSettingLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDBName, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDBMSPort, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHostName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldHostName)
                            .addComponent(jTextFieldDBName)
                            .addComponent(jTextFieldDBUserName)
                            .addComponent(jTextFieldDBPassword)
                            .addComponent(jTextFieldDBMSPort)
                            .addComponent(jLabelDBSetting, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))))
                .addContainerGap(521, Short.MAX_VALUE))
        );
        jPanelSettingLayout.setVerticalGroup(
            jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelDBSetting)
                .addGap(35, 35, 35)
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHostName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDBMSPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDBMSPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDBName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDBUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserName))
                .addGap(8, 8, 8)
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDBPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassword))
                .addGap(17, 17, 17)
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonApplyDBSetting)
                    .addComponent(jButtonChangeDBSetting))
                .addGap(230, 230, 230))
        );

        jTabbedPaneCRS.addTab("Setting", jPanelSetting);

        jLabelPreProcessing.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPreProcessing.setText("PRE-PROCESSING");

        jPanelDBExtraction.setBorder(javax.swing.BorderFactory.createTitledBorder("Extract Researchers, Tilte, Abstract of publications"));

        jLabelFrom.setText("From");

        jLabelTo.setText("To:");

        jFormattedTextFieldYearFrom.setText("1995");
        jFormattedTextFieldYearFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldYearFromActionPerformed(evt);
            }
        });

        jFormattedTextFieldYearTo.setText("2005");
        jFormattedTextFieldYearTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldYearToActionPerformed(evt);
            }
        });

        jButtonDBExtract.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonDBExtract.setText("Process");
        jButtonDBExtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDBExtractActionPerformed(evt);
            }
        });

        jLabelDirPath.setText("Output Path :");

        jButtonBrowse1.setText("Browse");
        jButtonBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowse1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDBExtractionLayout = new javax.swing.GroupLayout(jPanelDBExtraction);
        jPanelDBExtraction.setLayout(jPanelDBExtractionLayout);
        jPanelDBExtractionLayout.setHorizontalGroup(
            jPanelDBExtractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDBExtractionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDBExtractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFrom)
                    .addComponent(jLabelDirPath))
                .addGap(14, 14, 14)
                .addGroup(jPanelDBExtractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDBExtract)
                    .addGroup(jPanelDBExtractionLayout.createSequentialGroup()
                        .addComponent(jFormattedTextFieldYearFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldYearTo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDBExtractionLayout.createSequentialGroup()
                        .addComponent(jTextFieldPathDataExtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBrowse1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDBExtractionLayout.setVerticalGroup(
            jPanelDBExtractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDBExtractionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDBExtractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFrom)
                    .addComponent(jFormattedTextFieldYearFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldYearTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDBExtractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPathDataExtraction)
                    .addGroup(jPanelDBExtractionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDirPath)
                        .addComponent(jButtonBrowse1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDBExtract)
                .addGap(5, 5, 5))
        );

        jPanelRemoveStopwordStemming.setBorder(javax.swing.BorderFactory.createTitledBorder("Remove Stopword and Stemming"));

        jLabel1.setText("Source Dir:");

        jLabel2.setText("Output Path:");

        jButtonBrowse2.setText("Browse");
        jButtonBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowse2ActionPerformed(evt);
            }
        });

        jCheckBoxStopword.setText("Remove stopword");

        jCheckBoxStemming.setText("Stemming");

        jButtonStemming.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonStemming.setText("Process");
        jButtonStemming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStemmingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRemoveStopwordStemmingLayout = new javax.swing.GroupLayout(jPanelRemoveStopwordStemming);
        jPanelRemoveStopwordStemming.setLayout(jPanelRemoveStopwordStemmingLayout);
        jPanelRemoveStopwordStemmingLayout.setHorizontalGroup(
            jPanelRemoveStopwordStemmingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoveStopwordStemmingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRemoveStopwordStemmingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRemoveStopwordStemmingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonStemming)
                    .addGroup(jPanelRemoveStopwordStemmingLayout.createSequentialGroup()
                        .addComponent(jCheckBoxStopword)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxStemming))
                    .addGroup(jPanelRemoveStopwordStemmingLayout.createSequentialGroup()
                        .addGroup(jPanelRemoveStopwordStemmingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldStemOutPath, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                            .addComponent(jTextFieldStemmingSourcePath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBrowse2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRemoveStopwordStemmingLayout.setVerticalGroup(
            jPanelRemoveStopwordStemmingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoveStopwordStemmingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRemoveStopwordStemmingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldStemmingSourcePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowse2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRemoveStopwordStemmingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldStemOutPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRemoveStopwordStemmingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxStopword)
                    .addComponent(jCheckBoxStemming))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonStemming))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Format The InputData for Learning LDA"));

        jLabel3.setText("Source Dir:");

        jLabel4.setText("Output Path:");

        jButtonBrowse4.setText("Browse");
        jButtonBrowse4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowse4ActionPerformed(evt);
            }
        });

        jLabel_LDALib.setText("LDA-Lib");

        jComboBoxLDALib.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JGibbLDA", "MALLET-LDA" }));

        jButtonFormatInputLDA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonFormatInputLDA.setText("Process");
        jButtonFormatInputLDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFormatInputLDAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_LDALib)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFormatLDAPath)
                    .addComponent(jTextFieldFormatLDAOutFile)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFormatInputLDA, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxLDALib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBrowse4)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldFormatLDAPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowse4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldFormatLDAOutFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LDALib)
                    .addComponent(jComboBoxLDALib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButtonFormatInputLDA))
        );

        javax.swing.GroupLayout jPanelPreProcessingLayout = new javax.swing.GroupLayout(jPanelPreProcessing);
        jPanelPreProcessing.setLayout(jPanelPreProcessingLayout);
        jPanelPreProcessingLayout.setHorizontalGroup(
            jPanelPreProcessingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPreProcessingLayout.createSequentialGroup()
                .addGroup(jPanelPreProcessingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPreProcessingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelDBExtraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelPreProcessingLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabelPreProcessing, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPreProcessingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelRemoveStopwordStemming, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelPreProcessingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanelPreProcessingLayout.setVerticalGroup(
            jPanelPreProcessingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPreProcessingLayout.createSequentialGroup()
                .addComponent(jLabelPreProcessing)
                .addGap(8, 8, 8)
                .addComponent(jPanelDBExtraction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelRemoveStopwordStemming, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneCRS.addTab("PreProcessing", jPanelPreProcessing);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );

        jTabbedPaneCRS.addTab("Topic Model Learning", jPanel10);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Training Network", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jLabel6.setText("AuthorID_PaperID:");

        jLabel7.setText("PaperID_Year:");

        jButtonBrowse6.setText("Browse");

        jButtonBrowse7.setText("Browse");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTrainingAuthorPaperPath)
                    .addComponent(txtTrainingPaperYearPath, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBrowse7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBrowse6))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTrainingAuthorPaperPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowse6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBrowse7)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtTrainingPaperYearPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Testing Network", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jLabel8.setText("AuthorID_PaperID (NF):");

        jLabel9.setText("AuthorID_PaperID (FF):");

        jButtonBrowse8.setText("Browse");

        jButtonBrowse9.setText("Browse");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtNFAuthorPaperPath, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFFAuthorPaperPath, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBrowse9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBrowse8))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNFAuthorPaperPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowse8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFFAuthorPaperPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowse9)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecting Random Author", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jLabel10.setText("Existing Author List:");

        jButtonBrowse10.setText("Browse");

        radbtnUseListAuthor.setText("Using Existing List");
        radbtnUseListAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnUseListAuthorActionPerformed(evt);
            }
        });

        radbtnRadomAuthors.setSelected(true);
        radbtnRadomAuthors.setText("Random Authors");
        radbtnRadomAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnRadomAuthorsActionPerformed(evt);
            }
        });

        jLabel11.setText("Number of Random Authors");

        txtNumberOfRandomAuthor.setText("300");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumberOfRandomAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtListAuthorPath, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBrowse10))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(radbtnUseListAuthor)
                        .addGap(10, 10, 10)
                        .addComponent(radbtnRadomAuthors)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radbtnUseListAuthor)
                    .addComponent(radbtnRadomAuthors))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtListAuthorPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButtonBrowse10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNumberOfRandomAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Run Experiment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Link Based Methods", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jCheckBoxCosine.setSelected(true);
        jCheckBoxCosine.setText("Cosine");
        jCheckBoxCosine.setEnabled(false);

        jCheckBoxJaccard.setSelected(true);
        jCheckBoxJaccard.setText("Jaccard");
        jCheckBoxJaccard.setEnabled(false);

        jCheckBoxAdamicAdar.setSelected(true);
        jCheckBoxAdamicAdar.setText("Adamic-Adar");
        jCheckBoxAdamicAdar.setEnabled(false);

        jCheckBoxRSS.setSelected(true);
        jCheckBoxRSS.setText("RSS");
        jCheckBoxRSS.setEnabled(false);

        jCheckBoxMPVS.setSelected(true);
        jCheckBoxMPVS.setText("MPVS");
        jCheckBoxMPVS.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCosine)
                            .addComponent(jCheckBoxJaccard))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxRSS)
                            .addComponent(jCheckBoxMPVS))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jCheckBoxAdamicAdar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCosine)
                    .addComponent(jCheckBoxRSS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxJaccard)
                    .addComponent(jCheckBoxMPVS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxAdamicAdar))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trend Based Methods", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jCheckBoxRSSPlus.setSelected(true);
        jCheckBoxRSSPlus.setText("RSS+");
        jCheckBoxRSSPlus.setEnabled(false);

        jCheckBoxMPVSPlus.setSelected(true);
        jCheckBoxMPVSPlus.setText("MPVS+");
        jCheckBoxMPVSPlus.setEnabled(false);

        jLabel12.setText("Trend Coefficient (K):");

        jLabel13.setText("Year:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 109, Short.MAX_VALUE)
                        .addComponent(jCheckBoxRSSPlus)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxMPVSPlus)
                        .addGap(85, 85, 85))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValueK)
                            .addComponent(txtValueYear)))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxRSSPlus)
                    .addComponent(jCheckBoxMPVSPlus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtValueK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtValueYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Topic Model Methods", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        jCheckBoxKLDivergence.setSelected(true);
        jCheckBoxKLDivergence.setText("KL Divergence");
        jCheckBoxKLDivergence.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxKLDivergence)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxKLDivergence)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel14.setText("Save to:");

        jButtonBrowse11.setText("Browse");

        jButtonRun.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRun.setText("RUN EXPERIMENTS");
        jButtonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtResultPath)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonBrowse11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRun, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtResultPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBrowse11)
                        .addComponent(jButtonRun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("CO-AUTHOR PREDICTION");

        javax.swing.GroupLayout jPanelLinkPredictionLayout = new javax.swing.GroupLayout(jPanelLinkPrediction);
        jPanelLinkPrediction.setLayout(jPanelLinkPredictionLayout);
        jPanelLinkPredictionLayout.setHorizontalGroup(
            jPanelLinkPredictionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLinkPredictionLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLinkPredictionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLinkPredictionLayout.setVerticalGroup(
            jPanelLinkPredictionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLinkPredictionLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneCRS.addTab("Co-Author Prediction", jPanelLinkPrediction);

        mainMenuBar.setName("mainMenubar"); // NOI18N

        jMenuExperiment.setText("Experiment");

        jMenuItemPreProcessing.setText("Pre Propcessing");
        jMenuItemPreProcessing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPreProcessingActionPerformed(evt);
            }
        });
        jMenuExperiment.add(jMenuItemPreProcessing);

        jMenuItemLinkPrediction.setText("Link Prediction");
        jMenuItemLinkPrediction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLinkPredictionActionPerformed(evt);
            }
        });
        jMenuExperiment.add(jMenuItemLinkPrediction);

        mainMenuBar.add(jMenuExperiment);

        jMenuDBLP.setText("DBLP");
        mainMenuBar.add(jMenuDBLP);

        jMenuHelp.setText("Help");
        jMenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHelpActionPerformed(evt);
            }
        });

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        mainMenuBar.add(jMenuHelp);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCRS)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jTabbedPaneCRS, javax.swing.GroupLayout.PREFERRED_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPreProcessingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPreProcessingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPreProcessingActionPerformed

    private void jMenuItemLinkPredictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLinkPredictionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemLinkPredictionActionPerformed

    private void jMenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHelpActionPerformed
    }//GEN-LAST:event_jMenuHelpActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jTextFieldDBMSPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDBMSPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDBMSPortActionPerformed

    private void jButtonChangeDBSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeDBSettingActionPerformed
        // TODO add your handling code here:
        jTextFieldHostName.setEnabled(true);
        jTextFieldDBMSPort.setEnabled(true);
        jTextFieldDBName.setEnabled(true);
        jTextFieldDBUserName.setEnabled(true);
        jTextFieldDBPassword.setEnabled(true);
        jButtonApplyDBSetting.setEnabled(true);
    }//GEN-LAST:event_jButtonChangeDBSettingActionPerformed

    private void jFormattedTextFieldYearToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldYearToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldYearToActionPerformed

    private void jFormattedTextFieldYearFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldYearFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldYearFromActionPerformed

    private void jButtonApplyDBSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyDBSettingActionPerformed
        // TODO add your handling code here:
        jTextFieldHostName.setEnabled(false);
        jTextFieldDBMSPort.setEnabled(false);
        jTextFieldDBName.setEnabled(false);
        jTextFieldDBUserName.setEnabled(false);
        jTextFieldDBPassword.setEnabled(false);
        jButtonApplyDBSetting.setEnabled(false);
        jButtonChangeDBSetting.setEnabled(true);

        ConnectionService.dbUserName = jTextFieldDBUserName.getText();
        ConnectionService.dbPassword = jTextFieldDBPassword.getName();
        ConnectionService.dbURL = "jdbc:mysql://" + jTextFieldHostName.getText() + ":"
                + jTextFieldDBMSPort.getText() + "/" + jTextFieldDBName.getText()
                + "?useUnicode=true&characterEncoding=UTF-8";

    }//GEN-LAST:event_jButtonApplyDBSettingActionPerformed

    private void jButtonBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowse1ActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File file) {
                String extension = file.getName().toLowerCase();
                return extension.endsWith(".txt") || extension.endsWith("");
            }

            @Override
            public String getDescription() {
                return "Text file formatted by PubGuru Recommend";
            }
        });

        int returnValue = fc.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            jTextFieldPathDataExtraction.setText(file.getPath());
        }
    }//GEN-LAST:event_jButtonBrowse1ActionPerformed

    private void jButtonBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowse2ActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File file) {
                String extension = file.getName().toLowerCase();
                return extension.endsWith(".txt") || extension.endsWith("");
            }

            @Override
            public String getDescription() {
                return "Text file formatted by PubGuru Recommend";
            }
        });

        int returnValue = fc.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            jTextFieldStemmingSourcePath.setText(file.getPath());
            jTextFieldStemOutPath.setText(file.getPath());
            jTextFieldStemOutPath.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonBrowse2ActionPerformed

    private void jButtonBrowse4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowse4ActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File file) {
                String extension = file.getName().toLowerCase();
                return extension.endsWith(".txt") || extension.endsWith("");
            }

            @Override
            public String getDescription() {
                return "Text file formatted by PubGuru Recommend";
            }
        });

        int returnValue = fc.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            jTextFieldFormatLDAPath.setText(file.getPath());
            jTextFieldFormatLDAOutFile.setText(file.getPath());
            jTextFieldFormatLDAOutFile.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonBrowse4ActionPerformed

    private void jButtonDBExtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDBExtractActionPerformed
        try {
            System.out.println("-----------------------------------------------");
            System.out.println("START PROCESSING: ");
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Calendar cal = Calendar.getInstance();
            System.out.println(dateFormat.format(cal.getTime()));

            String rootPath = jTextFieldPathDataExtraction.getText();
            int yearFrom = Integer.parseInt(jFormattedTextFieldYearFrom.getText());
            int yearTo = Integer.parseInt(jFormattedTextFieldYearTo.getText());

            AuthorPaperBO authorPaperBO = new AuthorPaperBO();
            authorPaperBO.getAllPaperForEachAuthorOutToTextFile(rootPath, yearFrom, yearTo);

            cal = Calendar.getInstance();
            System.out.println(dateFormat.format(cal.getTime()));
            System.out.println("END PROCESSING: ");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonDBExtractActionPerformed

    private void jButtonStemmingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStemmingActionPerformed
        try {
            System.out.println("-----------------------------------------------");
            System.out.println("START PROCESSING: ");
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Calendar cal = Calendar.getInstance();
            System.out.println(dateFormat.format(cal.getTime()));

            String rootPath = jTextFieldStemmingSourcePath.getText();
            boolean isStem = jCheckBoxStemming.isSelected();

            TextParallelProcessor textProcessor = new TextParallelProcessor();
            File mainFolder = new File(rootPath);
            System.out.println(mainFolder.getAbsolutePath());
            File[] subFolderList = mainFolder.listFiles();
            for (int i = 0; i < subFolderList.length; i++) {
                if (subFolderList[i].isDirectory()) {
                    textProcessor.parallelProcess(rootPath, subFolderList[i].getPath(), subFolderList[i].getName(), isStem);
                }
            }

            cal = Calendar.getInstance();
            System.out.println(dateFormat.format(cal.getTime()));
            System.out.println("END PROCESSING: ");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonStemmingActionPerformed

    private void jButtonFormatInputLDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFormatInputLDAActionPerformed
        try {
            System.out.println("-----------------------------------------------");
            System.out.println("START PROCESSING: ");
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Calendar cal = Calendar.getInstance();
            System.out.println(dateFormat.format(cal.getTime()));

            String selectedLDALib = (jComboBoxLDALib.getSelectedItem()).toString();
            if (selectedLDALib.equalsIgnoreCase("JGibbLDA")) {
            }
            if (selectedLDALib.equalsIgnoreCase("MALLET-LDA")) {
            }

            cal = Calendar.getInstance();
            System.out.println(dateFormat.format(cal.getTime()));
            System.out.println("END PROCESSING: ");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonFormatInputLDAActionPerformed

    private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunActionPerformed
        int numberOfRandomAuthor = Integer.parseInt(txtNumberOfRandomAuthor.getText());
        boolean isCosineMethod = jCheckBoxCosine.isSelected();
        boolean isJaccardMethod = jCheckBoxJaccard.isSelected();
        boolean isAdarMethod = jCheckBoxAdamicAdar.isSelected();
        boolean isRSSMethod = jCheckBoxRSS.isSelected();
        boolean isRSSPlusMethod = jCheckBoxRSSPlus.isSelected();
        boolean isMPVSMethod = jCheckBoxMPVS.isSelected();
        boolean isMVVSPlusMethod = jCheckBoxMPVSPlus.isSelected();
        boolean isKLDivergence = jCheckBoxKLDivergence.isSelected();
        
        final Experiment experiment = new Experiment(txtTrainingAuthorPaperPath.getText(),
                txtTrainingPaperYearPath.getText(), txtNFAuthorPaperPath.getText(),
                txtFFAuthorPaperPath.getText(), txtListAuthorPath.getText(),
                txtValueK.getText(), txtValueYear.getText(),
                "2;4", txtResultPath.getText(),
                numberOfRandomAuthor, 
                isCosineMethod, isJaccardMethod, isAdarMethod, isRSSMethod,
                isRSSPlusMethod, isMPVSMethod, isMVVSPlusMethod, isKLDivergence);

        final DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = new Date();
        System.out.println("Started Time : " + dateFormat.format(date) + "\n");
        System.out.println("Processing ..." + "\n");
        ExecutorService executor = Executors.newFixedThreadPool(1);
        executor.submit(new Runnable() {
            @Override
            public void run() {
                try {
                    experiment.Run();
                    Date date = new Date();
                    System.out.println("Finished time : " + dateFormat.format(date) + "\n");
                    System.out.println("DONE !!!");
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
        executor.shutdown();
    }//GEN-LAST:event_jButtonRunActionPerformed

    private void radbtnUseListAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnUseListAuthorActionPerformed
        if (!radbtnUseListAuthor.isSelected()) {
            txtNumberOfRandomAuthor.setEnabled(true);
            return;
        } else {
            radbtnUseListAuthor.setSelected(true);
            radbtnRadomAuthors.setSelected(false);
            txtNumberOfRandomAuthor.setEnabled(false);
        }
    }//GEN-LAST:event_radbtnUseListAuthorActionPerformed

    private void radbtnRadomAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnRadomAuthorsActionPerformed
        if (!radbtnRadomAuthors.isSelected()) {
            txtNumberOfRandomAuthor.setEnabled(false);
            return;
        } else {
            txtNumberOfRandomAuthor.setEnabled(true);
            radbtnRadomAuthors.setSelected(true);
            radbtnUseListAuthor.setSelected(false);
            txtListAuthorPath.setText("");
        }
    }//GEN-LAST:event_radbtnRadomAuthorsActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRSMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRSMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRSMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRSMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRSMainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApplyDBSetting;
    private javax.swing.JButton jButtonBrowse1;
    private javax.swing.JButton jButtonBrowse10;
    private javax.swing.JButton jButtonBrowse11;
    private javax.swing.JButton jButtonBrowse2;
    private javax.swing.JButton jButtonBrowse4;
    private javax.swing.JButton jButtonBrowse6;
    private javax.swing.JButton jButtonBrowse7;
    private javax.swing.JButton jButtonBrowse8;
    private javax.swing.JButton jButtonBrowse9;
    private javax.swing.JButton jButtonChangeDBSetting;
    private javax.swing.JButton jButtonDBExtract;
    private javax.swing.JButton jButtonFormatInputLDA;
    private javax.swing.JButton jButtonRun;
    private javax.swing.JButton jButtonStemming;
    private javax.swing.JCheckBox jCheckBoxAdamicAdar;
    private javax.swing.JCheckBox jCheckBoxCosine;
    private javax.swing.JCheckBox jCheckBoxJaccard;
    private javax.swing.JCheckBox jCheckBoxKLDivergence;
    private javax.swing.JCheckBox jCheckBoxMPVS;
    private javax.swing.JCheckBox jCheckBoxMPVSPlus;
    private javax.swing.JCheckBox jCheckBoxRSS;
    private javax.swing.JCheckBox jCheckBoxRSSPlus;
    private javax.swing.JCheckBox jCheckBoxStemming;
    private javax.swing.JCheckBox jCheckBoxStopword;
    private javax.swing.JComboBox jComboBoxLDALib;
    private javax.swing.JFormattedTextField jFormattedTextFieldYearFrom;
    private javax.swing.JFormattedTextField jFormattedTextFieldYearTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDBMSPort;
    private javax.swing.JLabel jLabelDBName;
    private javax.swing.JLabel jLabelDBSetting;
    private javax.swing.JLabel jLabelDirPath;
    private javax.swing.JLabel jLabelFrom;
    private javax.swing.JLabel jLabelHostName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPreProcessing;
    private javax.swing.JLabel jLabelTo;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabel_LDALib;
    private javax.swing.JMenu jMenuDBLP;
    private javax.swing.JMenu jMenuExperiment;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemLinkPrediction;
    private javax.swing.JMenuItem jMenuItemPreProcessing;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelDBExtraction;
    private javax.swing.JPanel jPanelLinkPrediction;
    private javax.swing.JPanel jPanelPreProcessing;
    private javax.swing.JPanel jPanelRemoveStopwordStemming;
    private javax.swing.JPanel jPanelSetting;
    private javax.swing.JTabbedPane jTabbedPaneCRS;
    private javax.swing.JTextField jTextFieldDBMSPort;
    private javax.swing.JTextField jTextFieldDBName;
    private javax.swing.JTextField jTextFieldDBPassword;
    private javax.swing.JTextField jTextFieldDBUserName;
    private javax.swing.JTextField jTextFieldFormatLDAOutFile;
    private javax.swing.JTextField jTextFieldFormatLDAPath;
    private javax.swing.JTextField jTextFieldHostName;
    private javax.swing.JTextField jTextFieldPathDataExtraction;
    private javax.swing.JTextField jTextFieldStemOutPath;
    private javax.swing.JTextField jTextFieldStemmingSourcePath;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JRadioButton radbtnRadomAuthors;
    private javax.swing.JRadioButton radbtnUseListAuthor;
    private javax.swing.JTextField txtFFAuthorPaperPath;
    private javax.swing.JTextField txtListAuthorPath;
    private javax.swing.JTextField txtNFAuthorPaperPath;
    private javax.swing.JTextField txtNumberOfRandomAuthor;
    private javax.swing.JTextField txtResultPath;
    private javax.swing.JTextField txtTrainingAuthorPaperPath;
    private javax.swing.JTextField txtTrainingPaperYearPath;
    private javax.swing.JTextField txtValueK;
    private javax.swing.JTextField txtValueYear;
    // End of variables declaration//GEN-END:variables
}
