/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package uit.tkorg.crs.main;

/**
 *
 * @author Tin Huynh
 */
public class CRSMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form CRSMainFrame
     */
    public CRSMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneCRS = new javax.swing.JTabbedPane();
        jPanelSetting = new javax.swing.JPanel();
        jLabelDBSetting = new javax.swing.JLabel();
        jLabelHostName = new javax.swing.JLabel();
        jLabelDBMSPort = new javax.swing.JLabel();
        jLabelDBName = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldHostName = new javax.swing.JTextField();
        jTextFieldDBMSPort = new javax.swing.JTextField();
        jTextFieldDBName = new javax.swing.JTextField();
        jTextFieldDBUserName = new javax.swing.JTextField();
        jTextFieldDBPassword = new javax.swing.JTextField();
        jButtonApplyDBSetting = new javax.swing.JButton();
        jButtonChangeDBSetting = new javax.swing.JButton();
        jPanelPreProcessing = new javax.swing.JPanel();
        jPanelLinkPrediction = new javax.swing.JPanel();
        mainMenuBar = new javax.swing.JMenuBar();
        jMenuExperiment = new javax.swing.JMenu();
        jMenuItemPreProcessing = new javax.swing.JMenuItem();
        jMenuItemLinkPrediction = new javax.swing.JMenuItem();
        jMenuDBLP = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRS Framework");

        jLabelDBSetting.setText("DATABASE CONNECTION SETTING");

        jLabelHostName.setText("Host name:");

        jLabelDBMSPort.setText("Port");

        jLabelDBName.setText("DB Name:");

        jLabelUserName.setText("Username:");

        jLabelPassword.setText("Password:");

        jTextFieldHostName.setText("localhost");
        jTextFieldHostName.setToolTipText("");
        jTextFieldHostName.setEnabled(false);

        jTextFieldDBMSPort.setText("3306");
        jTextFieldDBMSPort.setEnabled(false);
        jTextFieldDBMSPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDBMSPortActionPerformed(evt);
            }
        });

        jTextFieldDBName.setText("MAS");
        jTextFieldDBName.setEnabled(false);

        jTextFieldDBUserName.setText("root");
        jTextFieldDBUserName.setEnabled(false);

        jTextFieldDBPassword.setText("root");
        jTextFieldDBPassword.setEnabled(false);

        jButtonApplyDBSetting.setText("Apply");
        jButtonApplyDBSetting.setEnabled(false);

        jButtonChangeDBSetting.setText("Change");
        jButtonChangeDBSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeDBSettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSettingLayout = new javax.swing.GroupLayout(jPanelSetting);
        jPanelSetting.setLayout(jPanelSettingLayout);
        jPanelSettingLayout.setHorizontalGroup(
            jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingLayout.createSequentialGroup()
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSettingLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButtonApplyDBSetting)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonChangeDBSetting))
                    .addGroup(jPanelSettingLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDBName, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDBMSPort, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHostName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldHostName)
                            .addComponent(jTextFieldDBName)
                            .addComponent(jTextFieldDBUserName)
                            .addComponent(jTextFieldDBPassword)
                            .addComponent(jTextFieldDBMSPort)
                            .addComponent(jLabelDBSetting, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanelSettingLayout.setVerticalGroup(
            jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelDBSetting)
                .addGap(35, 35, 35)
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHostName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDBMSPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDBMSPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDBName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDBUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserName))
                .addGap(8, 8, 8)
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDBPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassword))
                .addGap(17, 17, 17)
                .addGroup(jPanelSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonApplyDBSetting)
                    .addComponent(jButtonChangeDBSetting))
                .addGap(230, 230, 230))
        );

        jTabbedPaneCRS.addTab("Setting", jPanelSetting);

        javax.swing.GroupLayout jPanelPreProcessingLayout = new javax.swing.GroupLayout(jPanelPreProcessing);
        jPanelPreProcessing.setLayout(jPanelPreProcessingLayout);
        jPanelPreProcessingLayout.setHorizontalGroup(
            jPanelPreProcessingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        jPanelPreProcessingLayout.setVerticalGroup(
            jPanelPreProcessingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jTabbedPaneCRS.addTab("PreProcessing", jPanelPreProcessing);

        javax.swing.GroupLayout jPanelLinkPredictionLayout = new javax.swing.GroupLayout(jPanelLinkPrediction);
        jPanelLinkPrediction.setLayout(jPanelLinkPredictionLayout);
        jPanelLinkPredictionLayout.setHorizontalGroup(
            jPanelLinkPredictionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        jPanelLinkPredictionLayout.setVerticalGroup(
            jPanelLinkPredictionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jTabbedPaneCRS.addTab("Link Prediction", jPanelLinkPrediction);

        mainMenuBar.setName("mainMenubar"); // NOI18N

        jMenuExperiment.setText("Experiment");

        jMenuItemPreProcessing.setText("Pre Propcessing");
        jMenuItemPreProcessing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPreProcessingActionPerformed(evt);
            }
        });
        jMenuExperiment.add(jMenuItemPreProcessing);

        jMenuItemLinkPrediction.setText("Link Prediction");
        jMenuItemLinkPrediction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLinkPredictionActionPerformed(evt);
            }
        });
        jMenuExperiment.add(jMenuItemLinkPrediction);

        mainMenuBar.add(jMenuExperiment);

        jMenuDBLP.setText("DBLP");
        mainMenuBar.add(jMenuDBLP);

        jMenuHelp.setText("Help");
        jMenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHelpActionPerformed(evt);
            }
        });

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        mainMenuBar.add(jMenuHelp);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCRS)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneCRS)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPreProcessingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPreProcessingActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItemPreProcessingActionPerformed

    private void jMenuItemLinkPredictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLinkPredictionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemLinkPredictionActionPerformed

    private void jMenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHelpActionPerformed
        
    }//GEN-LAST:event_jMenuHelpActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jTextFieldDBMSPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDBMSPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDBMSPortActionPerformed

    private void jButtonChangeDBSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeDBSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChangeDBSettingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRSMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRSMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRSMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRSMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRSMainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApplyDBSetting;
    private javax.swing.JButton jButtonChangeDBSetting;
    private javax.swing.JLabel jLabelDBMSPort;
    private javax.swing.JLabel jLabelDBName;
    private javax.swing.JLabel jLabelDBSetting;
    private javax.swing.JLabel jLabelHostName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JMenu jMenuDBLP;
    private javax.swing.JMenu jMenuExperiment;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemLinkPrediction;
    private javax.swing.JMenuItem jMenuItemPreProcessing;
    private javax.swing.JPanel jPanelLinkPrediction;
    private javax.swing.JPanel jPanelPreProcessing;
    private javax.swing.JPanel jPanelSetting;
    private javax.swing.JTabbedPane jTabbedPaneCRS;
    private javax.swing.JTextField jTextFieldDBMSPort;
    private javax.swing.JTextField jTextFieldDBName;
    private javax.swing.JTextField jTextFieldDBPassword;
    private javax.swing.JTextField jTextFieldDBUserName;
    private javax.swing.JTextField jTextFieldHostName;
    private javax.swing.JMenuBar mainMenuBar;
    // End of variables declaration//GEN-END:variables
}
